
// this page contains data to be added to articles when user excecutes functions
// each article is assigned a unique number that is used to fetch the article from loadArticle function
const headlines = [{
  "title": "Malaysia border reopening on Apr 1: What travellers need to know",
  "author": "Vincent Tan",
  "date": "09 Mar 2022 05:08PM",
  "h3": ["WHAT ARE THE HEALTH PROTOCOLS FOR FOREIGNERS ENTERING MALAYSIA?","WHAT HAS CHANGED FOR MALAYSIANS TRAVELLING OVERSEAS?","WHAT DOES THIS MEAN FOR TRAVEL BETWEEN SINGAPORE AND MALAYSIA?"],
  "image": ["images/Border opening image 1.jpg", "images/Border opening image 2.jpg"],
  "imgDesc": ["The Causeway at dusk. (Photo: iStock)", "Health Minister Khairy Jamaluddin (right) and Health Ministry director-general Noor Hisham Abdullah in a press conference on Mar 9, 2022. (Screengrab: Facebook/Health Ministry of Malaysia)"],
  "description": "Two years after Malaysia closed its borders on Mar 18, 2020 in the wake of a global pandemic, Prime Minister Ismail Sabri Yaakob announced that the country will reopen fully on Apr 1.",
  "paragraph1":"KUALA LUMPUR: Two years after Malaysia closed its borders on Mar 18, 2020 in the wake of a global pandemic, Prime Minister Ismail Sabri Yaakob announced that the country will reopen fully on Apr 1.",
  "paragraph2": ["Mr Ismail Sabri said in a press conference on Tuesday (Mar 8) that this reopening is part of its “Transitioning to Endemicity” phase. In line with that, the government will also lift a slew of domestic restrictions on business operating hours, employee capacity as well as capacity limits on mosque prayers and other houses of worship."],
  "paragraph3": ["However, given COVID-19’s Omicron variant spread in both Malaysia and internationally, Malaysians and foreign travellers entering the country will need to adhere to some protocols, although restrictions have been loosened."],
  "paragraph4": ["Here’s what travellers need to know about the borders reopening:"],
  "paragraph5": ["Beginning Apr 1, foreigners entering Malaysia with valid travel documents do not need to undergo quarantine, so long as they are fully vaccinated"],
  "paragraph6": ["The requirement for foreigners to apply to enter Malaysia using the MyTravelPass application will also be lifted."],
  "paragraph7": ["Instead, they only need to download and activate the MySejahtera contact tracing app and fill up a pre-departure form in the app."],
  "paragraph8": ["Travellers need to undergo a COVID-19 reverse transcription-polymerase chain reaction (RT-PCR) test two days before departure, and another professional COVID-19 antigen rapid test (RTK-Ag) within 24 hours after arrival."],
  "paragraph9": ["Health Minister Khairy Jamaluddin explained in a press conference on Wednesday that travellers who are not fully vaccinated or unvaccinated will need to undergo a five-day quarantine after arriving in Malaysia. This is shortened from the current requirement of 10 days."],
  "paragraph10": ["“After they exit quarantine, the individual must adhere to the conditions set by the Malaysian government. For example, they cannot dine at restaurants if they are not fully vaccinated,” the minister said."],
  "paragraph11": ["For travellers who have health reasons to remain unvaccinated, they will need to upload proof of their exemption, such as a doctor’s letter, in their MySejahtera app."],
  "paragraph12": ["“The exemption will be evaluated by the Health Ministry to determine its authenticity."],
  "paragraph13": ["“After the evaluation is done and it is determined to be authentic, they will get a health exemption,” Mr Khairy added."],
  "paragraph14": ["Travellers who enter Malaysia in the last week of March will be released from quarantine on Apr 1, the minister said. Currently, vaccinated travellers are required to observe a five-day quarantine period for those who have taken their booster doses, or seven-day for those without booster doses."],
  "paragraph15": ["Additionally, quarantine-free entry is allowed for children and teenagers below the age of 17, regardless of their vaccination status."],
  "paragraph16": ["Like other travellers, they are also required to undergo a pre-departure RT-PCR and post-arrival RTK-Ag test."],
  "paragraph17": ["Similarly, Malaysians with valid travel documents are allowed to travel overseas to countries which have also opened their international borders for travel."],
  "paragraph18": ["Fully vaccinated Malaysians do not need to undergo quarantine upon returning to Malaysia. They also have to fulfil the pre-departure RT-PCR and post-arrival RTK-Ag test requirements."],
  "paragraph19": ["For countries which are still closing their borders, Malaysians can make use of the vaccinated travel lanes (VTLs) which have been agreed upon between the Malaysian government and related countries"],
  "paragraph20": ["Malaysia has land and air VTL agreements with Singapore since late 2021. Its VTLs with Thailand, Brunei and Indonesia are in the works."],
  "paragraph21": ["With Malaysia’s announcement, travellers from Singapore can enter Malaysia from Apr 1 quarantine-free as long as they are fully vaccinated."],
  "paragraph22": ["However, they will still be subject to quarantine requirements imposed by Singapore upon their return, if they are not travelling via VTL. There is reportedly a daily quota of 4,320 people both ways for those using the land VTL between Singapore and Malaysia. The cap for the air VTL has not been disclosed"],
  "paragraph23": ["SIngapore’s Ministry of Trade and Industry (MITI) said on Tuesday that it is working with its Malaysian counterparts to allow vaccinated travellers to cross the land border through other transport modes."],
  "paragraph24": ["In his Wednesday press conference, Mr Khairy said the federal government is in discussions with states that have international borders as well as neighbouring countries on the issue."],
  "paragraph25": ["As such, details on international land travel will only be announced next week, he added, as the protocols have to distinguish between travellers entering for tourism and periodic commuters."],
  "articleNumber" : "1",
  },
  {
    "title": "Daily passenger quota for land VTL between Malaysia and Singapore to increase",
    "author": "Cheryl Lin",
    "date": "10 Mar 2022 07:25PM",
    "h3": ["PERSONAL INCOME TAX", "CHANGES TO PROPERTY TAX", "TAX ON LUXURY CARS"],
    "image": ["images/VTL image 1.jpg","images/VTL image 2.png"],
    "imgDesc": ["Travellers wait in line at the vaccinated travel lane bus counters at Larkin Station in Johor Bahru on Dec 6, 2021. (Photo: Low Zoey)", "The enhanced assurance package aims to offset at least 5 years of additional GST expenses for the majority of Singapore households. (Graphic: Rafa Estrada)", "The enhanced GST Assurance Package will provide these payouts over the next five years. (Graphic: Rafa Estrada)", "How might the financial help announced in Budget 2022 go towards offsetting the GST increase? Here are some scenarios. (Infographic: Clara Ho)", "Starting from the Aug 2022 payout the annual income threshold for the enhanced GST Voucher - Cash scheme will be increased to S$34,000. (Graphic: Rafa Estrada)"],
    "description": "The daily passenger quota under the land vaccinated travel lane (VTL) between Singapore and Malaysia will be increased from Monday (Mar 14), both countries announced on Thursday.",
    "paragraph1": ["SINGAPORE: The daily passenger quota under the vaccinated travel lane (VTL) by land between Singapore and Malaysia will be increased, Malaysia’s Ministry of Transport announced on Thursday (Mar 10)."],
    "paragraph2": ["The daily quota will rise from 2,160 to 3,420 from Mar 14. The sale of bus tickets for the additional seats will start on Friday for travel from Mar 14."],
    "paragraph3": ["We are progressively expanding the VTL with Malaysia via our land borders, to allow more travellers to travel across the borders, said a spokesperson for Singapore's Ministry of Trade and Industry (MTI)."],
    "paragraph4": ["“This would allow even more fully vaccinated people to travel across the Causeway without being subject to quarantine and other related requirements,” said Malaysia’s transport ministry."],
    "paragraph5": ["Malaysia’s designated bus operator will continue to operate the VTL by land to Singapore from the Larkin Terminal in Johor Bahru, it added."],
    "paragraph6": ["Earlier this week, Malaysia’s Prime Minister Ismail Sabri Yaakob announced that the country will fully reopen its borders on Apr 1 as it begins to transition to the COVID-19 endemic phase."],
    "paragraph7": ["Travellers who are fully vaccinated will not need to undergo quarantine. They will only need to do a COVID-19 reverse transcription-polymerase chain reaction (RT-PCR) test two days before departure and a professional COVID-19 rapid test kit-antigen (RTK-Ag) test within 24 hours after arrival in Malaysia."],
    "paragraph9": ["Singapore’s Ministry of Trade and Industry said on Tuesday that it is working with its Malaysian counterparts to expand the land VTL to allow vaccinated travellers to cross the border via other transport routes."],
    "paragraph10": ["In an effort to slow the spread of the Omicron variant, Singapore froze all new VTL ticket sales between Dec 23 and Jan 20, and reduced the quotas after Jan 20. The quota for VTL (Land) was fully restored on Feb 22. "],
    "paragraph11": ["Singapore currently has land and air VTLs with Malaysia."],
    "paragraph11": ["Under the land VTL, travellers are able to commute between Singapore and Johor Bahru by taking designated bus services across the Causeway. The bus services are operated by two companies, Transtar Travel and Handal Indah."],
    "paragraph12": ["Travellers need to obtain a negative pre-departure polymerase chain reaction (PCR) test result or antigen rapid test (ART) result within two days before departure for Singapore."],
    "paragraph13": ["Upon arrival in Singapore, they can take a supervised self-administered ART at Woodlands and Queen Street Bus Terminals, or choose to take the test at any quick test centre or combined test centre within 24 hours of arrival in Singapore."],
    "paragraph14":["We will continue to review our border measures and expand VTL (Land) in a safe and progressive manner, taking into account the public health situation in both countries and globally, said MTI."],
    "paragraph15": ["Under the air VTL, there are designated flights between Changi Airport and Kuala Lumpur International Airport."],
    "paragraph16": ["From Mar 16, the air VTL for Malaysia will extend beyond Kuala Lumpur to include Penang, starting with four daily flights each way between Singapore and Penang."],
    "articleNumber" : "2",
  }
];

const finance = [{
  "title": "Budget 2022: Higher taxes for top-tier earners, high-end properties and luxury cars",
  "author": "Tang See Kit",
  "date": "18 Feb 2022 05:37PM",
  "h3": ["PERSONAL INCOME TAX", "CHANGES TO PROPERTY TAX", "TAX ON LUXURY CARS"],
  "image": ["images/budget 2022 img1.jpg", "images/budget 2022 img2.png"],
  "imgDesc": ["“Singapore is in a very strong position despite the pandemic as far as real estate is concerned,” said Ismail Gafoor, chief executive of PropNex Realty, Singapore’s largest private real estate company. (Photo: Unsplash/Mike Enerio)", "Singapore’s GST hike has been delayed to 2023 and the increase will be staggered over 2 years. (Graphic: Dawn Teo)", "The enhanced assurance package aims to offset at least 5 years of additional GST expenses for the majority of Singapore households. (Graphic: Rafa Estrada)", "The enhanced GST Assurance Package will provide these payouts over the next five years. (Graphic: Rafa Estrada)", "How might the financial help announced in Budget 2022 go towards offsetting the GST increase? Here are some scenarios. (Infographic: Clara Ho)", "Starting from the Aug 2022 payout the annual income threshold for the enhanced GST Voucher - Cash scheme will be increased to S$34,000. (Graphic: Rafa Estrada)"],
  "description": "The Government will delay the planned Goods and Services Tax (GST) hike to 2023 and stagger the increase in two steps, Finance Minister Lawrence Wong said in his Budget speech",
  "embeddedVideo1": ['<iframe width="572" height="322" src="https://www.youtube.com/embed/PcQRTkyb4rU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'],
  "embeddedVideo2": ['<iframe width="572" height="322" src="https://www.youtube.com/embed/rivvr_x5Xyo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'],
  "embeddedVideo3": ['<iframe width="591" height="333" src="https://www.youtube.com/embed/rivvr_x5Xyo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'],
  "paragraph1": ["SINGAPORE: Singapore will be raising the personal income tax rate for top-tier earners, alongside adjustments to property taxes and an additional levy on luxury cars."],
  "paragraph2": ["These new taxes are part of “major enhancements” to Singapore’s tax regime announced by Finance Minister Lawrence Wong in his Budget 2022 speech on Friday (Feb 18)."],
  "paragraph3": ["Mr Wong, in his speech, had outlined a range of near-term aid and long-term measures to continue investing in the economy and workers, while strengthening the social compact. Tax changes are hence necessary to meet the need for more revenue to bring these initiatives into fruition, he said."],
  "paragraph4": ["Noting that there is room for “greater progressivity” when it comes to personal income taxes “so that those who earn more, contribute more”, Mr Wong announced that the top marginal personal income tax rate will be raised from the Year of Assessment 2024."],
  "paragraph5": ["The portion of chargeable income in excess of S$500,000 and up to S$1 million will be taxed at 23 per cent, up from the current 22 per cent levied on the portion of chargeable income in excess of S$320,000."],
  "paragraph6": ["For the portion of chargeable income in excess of S$1 million, the personal income tax rate will go up to 24 per cent from the existing 22 per cent."],
  "paragraph7": ["This increase is set to affect the top 1.2 per cent of personal income taxpayers, Mr Wong said."],
  "paragraph8": ["It is expected to raise S$170 million of additional tax revenue per year."],
  "paragraph9": ["Property taxes, which Mr Wong described as Singapore’s “principal means of taxing wealth”, will also be raised, with changes set to be rolled out in two phases over the next two years."],
  "paragraph10": ["First, all non-owner occupied residential properties will see higher taxes, with the increase being more significant for properties at the high end."],
  "paragraph11": ["Currently at 10 to 20 per cent, the tax rates for such properties, which include investment properties, will first be raised to 11 to 27 per cent in 2023, before being raised further to 12 to 36 per cent in 2024."],
  "paragraph12": ["For example, a large non-owner-occupied detached house located in the central area with an annual value of S$150,000 will see an annual property tax bill of about S$43,000 a year, up from the existing S$24,000."],
  "paragraph13": ["Second, tax rates for owner-occupied residential properties with annual values of more than S$30,000 will also be raised."],
  "paragraph14": ["Currently, the taxation rate ranges from 4 to 16 per cent beyond the first S$8,000 of a property’s annual value. Under the new changes, there will be a taxation range of 5 to 23 per cent beyond the first S$30,000 valuation by 2023, with a further increase to 6 to 32 per cent in 2024."],
  "paragraph15": ["This increase will impact the top seven per cent of owner-occupied residential properties, such as condominiums located in central Singapore and large landed properties, with steeper tax increases for those at the top end. "],
  "paragraph16": ["When fully implemented, these two changes to the property tax will raise Singapore’s property tax revenue by about S$380 million a year."],
  "paragraph17": ["Singapore will also start levying higher taxes on luxury cars to make its vehicle tax system “more progressive”."],
  "paragraph18": ["It will do so by introducing a new additional registration fee (ARF) tier for cars at a rate of 220 per cent for the portion of open market value in excess of S$80,000."],
  "paragraph19": ["The new rates will apply to all cars registered with COEs obtained from the second COE bidding round this month."],
  "paragraph20": ["This is expected to generate an additional S$50 million in revenue per year."],
  "paragraph21": ["These announcements come as the idea of wealth taxes has gathered momentum over the course of the pandemic, in Singapore and around the world."],
  "paragraph22": ["Mr Wong said wealth taxes are an important part of Singapore’s tax system."],
  "paragraph23": ["“Apart from generating revenue, they also help to recirculate a portion of the wealth stock into our economy and in so doing, mitigate social inequalities. Wealth taxes are therefore needed to build a fairer society where everyone can aspire to succeed regardless of their backgrounds,” he said."],
  "paragraph24": ["At the moment, Singapore is already taxing wealth in several ways such as property tax and stamp duties on residential properties, as well as additional registration fees on motor vehicles."],
  "paragraph25": ["While Singapore would ideally want to tax the net wealth of individuals, such a tax is not easy to implement effectively, said Mr Wong."],
  "paragraph26": ["Many forms of wealth are “mobile”, he said, while estimating wealth accurately and fairly can be a “more complex exercise” than estimating incomes."],
  "paragraph27": ["Singapore is not alone in facing such challenges he said, noting how some countries like Germany and France have stopped levying taxes on net wealth of individuals."],
  "paragraph28": ["The number of OECD countries with net wealth taxes has also dropped from 12 in 1990 to three in 2020, partly due to difficulties in effectively implementing such taxes."],
  "paragraph29": ["“We will continue to study the experiences of other countries and explore options to tax wealth effectively. In the meantime, we will strengthen our current system of taxes,” Mr Wong said."],
  "articleNumber" : "3",
  },
  {
    "title": "Budget 2022: GST will go up to 8% next year, then 9% from 2024; extra S$640 million to cushion impact",
    "author": "Aqil Haziq Mahmud",
    "date": "18 Feb 2022 05:23PM",
    "h3": ["CUSHIONING THE IMPACT", "GST VOUCHER SCHEME IMPROVEMENTS"],
    "image": ["images/GST 2022 img1.jpg", "images/GST 2022 img2.png", "images/GST 2022 img3", "images/GST 2022 img4", "images/GST 2022 img5", "images/GST 2022 img6"],
    "imgDesc": ["File photo of a shopper at a Singapore supermarket. (Photo: MCI)", "Singapore’s GST hike has been delayed to 2023 and the increase will be staggered over 2 years. (Graphic: Dawn Teo)", "The enhanced assurance package aims to offset at least 5 years of additional GST expenses for the majority of Singapore households. (Graphic: Rafa Estrada)", "The enhanced GST Assurance Package will provide these payouts over the next five years. (Graphic: Rafa Estrada)", "How might the financial help announced in Budget 2022 go towards offsetting the GST increase? Here are some scenarios. (Infographic: Clara Ho)", "Starting from the Aug 2022 payout the annual income threshold for the enhanced GST Voucher - Cash scheme will be increased to S$34,000. (Graphic: Rafa Estrada)"],
    "description": "The Government will delay the planned Goods and Services Tax (GST) hike to 2023 and stagger the increase in two steps, Finance Minister Lawrence Wong said in his Budget speech",
    "embeddedVideo1": ['<iframe width="697" height="392" src="https://www.youtube.com/embed/TsCLAOFL4EU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'],
    "embeddedVideo2": ['<iframe width="697" height="392" src="https://www.youtube.com/embed/DroOq4tdjCs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'],
    "paragraph1": ["SINGAPORE: The Government will delay the planned Goods and Services Tax (GST) hike to 2023 and stagger the increase in two steps, Finance Minister Lawrence Wong said in his Budget speech on Friday (Feb 18)."],
    "paragraph2": ["The first increase from 7 per cent to 8 per cent will take place on Jan 1, 2023, and the second increase from 8 per cent to 9 per cent will take place on Jan 1, 2024."],
    "paragraph3": ["This comes after Prime Minister Lee Hsien Loong said in his New Year message in December that the Government will have to start moving on the planned hike this year, given that the economy is emerging from COVID-19."],
    "paragraph4": ["The plan to raise the GST by two percentage points, from 7 per cent to 9 per cent, was first announced in 2018 during then-Finance Minister Heng Swee Keat’s Budget speech."],
    "paragraph5": ["Mr Wong said on Friday that the GST hike is necessary to support Singapore’s healthcare expenditure and to take care of its seniors."],
    "paragraph6": ["On the timing, Mr Wong said he has considered the overall situation – the pandemic, the state of Singapore’s economy and the inflation outlook."],
    "paragraph7": ["“Our revenue needs are pressing. But I also understand the concerns that Singaporeans have about the GST increase taking place at the same time as rising prices.”"],
    "paragraph8": ["The Government will continue to absorb GST on publicly subsidised healthcare and education, he said. Town councils will get an additional S$15 million a year to cover the additional GST payable on service and conservancy charges."],
    "paragraph9": ["Government fees and charges will not rise in 2023. This applies to licence fees, as well as fees charged by government agencies for the provision of services. This includes school fees, Institute of Technical Education and polytechnic fees, and public car park charges."],
    "paragraph10": ["“To address concerns that businesses could use GST as a cover to raise prices, the Government will stand up a Committee Against Profiteering,” Mr Wong said, adding that it will be chaired by Minister of State for Trade and Industry Low Yen Ling."],
    "paragraph11": ["To cushion the impact of the GST hike, the Government will add S$640 million to the S$6 billion Assurance Package – announced in 2020 – and improve the GST Voucher (GSTV) scheme."],
    "paragraph12": ["Both the Assurance Package and improved GSTV scheme will be implemented together before the GST hike so Singaporeans can benefit from both at the same time, Mr Wong said."],
    "paragraph13": ["The enhanced Assurance Package will cover at least five years of additional GST expenses for the majority of Singaporean households, and about 10 years for lower-income households, he said."],
    "paragraph14": ["Under the package, every adult Singaporean will get cash payouts of between S$700 and S$1,600, while eligible seniors will get a special GSTV – Cash (Seniors’ Bonus) of between S$600 and S$900."],
    "paragraph15": ["Eligible Housing Board households will get extra U-Save rebates of S$330 to S$570 depending on flat type, while all Singaporean children and seniors will get MediSave top-ups of S$450."],
    "paragraph16": ["All Singaporean households will also get two tranches of CDC vouchers worth S$200 each in 2023 and 2024. The vouchers can be used at all participating heartland merchants and hawkers as well as major supermarkets."],
    "paragraph17": ["“Even with these offsets, some vulnerable households may require more support,” Mr Wong said, adding that those with urgent needs can approach their Citizens’ Consultative Committees (CCC) for help."],
    "paragraph18": ["The Government will top up the CCC ComCare Fund by S$5 million over five years and provide self-help groups with a total of S$12 million over four years."],
    "paragraph19": ["Close to S$40 million will be set aside under the Productivity Solutions Grant for businesses to apply for subsidised accounting and point-of-sale solutions."],
    "paragraph20": ["The permanent GSTV scheme currently has three components: Cash payout, MediSave top-up and utilities rebates."],
    "paragraph21": ["Under the improvements, the service and conservancy charges rebate will be made a permanent component of the GSTV scheme."],
    "paragraph22": ["The assessable income threshold for GSTV – Cash will be increased from S$28,000 to S$34,000 to cover more Singaporeans."],
    "paragraph23": ["The GSTV – Cash quantum will also be increased to S$500 for those living in homes with annual values of S$13,000 and below; and to S$250 for those living in homes with annual values of between S$13,000 and S$21,000."],
    "paragraph24": ["For instance, the improved GSTV will fully offset the total GST that retiree households living in one- to four-room HDB flats have to pay, while many retiree households in bigger flats will also have their GST offset by a “significant amount”, he said."],
    "paragraph25": ["“For low-income households who do not have elderly members, the GSTV will offset about half their total GST expenses every year,” he added."],
    "paragraph26": ["Mr Wong said low-income households in particular will be “well looked after”, adding that the measures ensure they get “significant support on a continuing basis”."],
    "paragraph27": ["“This is why the GST increase will not hurt low-income households. For them, the impact of the increase in GST will be neutralised.”"],
    "articleNumber" : "4",


  }
];

const sports = [{
  "title": "PSG face rebuild after latest European capitulation",
  "date": "10 Mar 2022 11:20PM",
  "h3": ['REALLY DISAPPOINTED AND UPSET'],
  "image": ["images/PSG Image 1.jpg", "images/PSG Image 2.jpg"],
  "imgDesc": ["Kylian Mbappe scored in both legs against Real Madrid but finished on the losing side (Photo: AFP/GABRIEL BOUYS)", "Lionel Messi (R) was a peripheral figure as Karim Benzema took centre stage in Madrid (Photo: AFP/GABRIEL BOUYS)"],
  "description": "Masters of their own downfall once more, Paris Saint-Germain's latest Champions League collapse is likely to set in motion sweeping changes after the club again fell short of its ultimate goal",
  "paragraph1": ["PARIS: Masters of their own downfall once more, Paris Saint-Germain's latest Champions League collapse is likely to set in motion sweeping changes after the club again fell short of its ultimate goal"],
  "paragraph2": ["For the fourth time in six seasons PSG crashed out in the last 16 of a competition they cherish most, finding more ways to lose a tie they dominated against the 13-time European champions Real Madrid."],
  "paragraph3": ["While less spectacular than the 2017 implosion against Barcelona at Camp Nou, Wednesday's meek disintegration from a position of strength underlined the enduring fragility of a squad scarred by repeated failures"],
  "paragraph4": ["Crucially, it was also a defeat that could spell the end of Kylian Mbappe's time in Paris, with his contract up in July and an expected dream move to Madrid appearing all the more probable."],
  "paragraph5": ["The France star scored in both legs, and another Mbappe masterclass in Spain had Madrid trailing 2-0 on aggregate before Karim Benzema's 17-minute hat-trick floored PSG."],
  "paragraph6": ["Beaten by one of their own, Paris-born Kingsley Coman, in the 2020 final against Bayern Munich, the trumpeted signing of Lionel Messi was supposed to be the missing piece of the jigsaw."],
  "paragraph7": ["But it simply hasn't happened for the Argentine, proudly paraded by PSG in December after winning a seventh Ballon d'Or but who has looked a shadow of the player that reigned in Barcelona."],
  "paragraph8": ["His missed penalty in the first leg ought to have been rendered insignificant, but the nature in which Mbappe, Messi and Neymar were effectively taken out of the game once Madrid equalised on the night at the Santiago Bernabeu ensured it won't be forgotten"],
  "paragraph9": ["With only the league to focus on for the remainder of the campaign, the next few months will be a time for soul-searching after another season of unfulfilled ambitions."],
  "paragraph10": ["It's going to be tough because the objective for Paris Saint-Germain is chasing the Champions League. It has been for many years, said PSG coach Mauricio Pochettino."],
  "paragraph11": ["We're really disappointed and upset. It's not going to be easy to change this feeling in the next few days"],
  "paragraph12": ["Club president Nasser Al-Khelaifi and sporting director Leonardo launched an angry tirade in the referee's dressing room, but Pochettino is the one most likely to pay the price."],
  "paragraph13": ["You can lose against Real Madrid because they're one of the best teams in the world but the way it happened is difficult to accept, said the former Tottenham boss."],
  "paragraph14": ["The hope was that PSG could persuade Mbappe, a generational talent, to sign a new contract with victory over Madrid."],
  "paragraph15": ["Instead PSG wilted in all too familiar fashion, almost resigned to their fate, and Mbappe was forced to watch his friend Benzema soak up the adulation of the Madrid fans"],
  "paragraph16": ["Renewed speculation over the potential appointment of Zinedine Zidane is sure to follow, but the departure of Mbappe would leave the club drifting further away from European glory than ever in recent times."],
  "paragraph17": ["Mbappe's arrival in 2017 coincided with the world-record signing of Neymar, whose run of injuries in the capital have often come at the least opportune moments."],
  "paragraph18": ["But after a busy summer of recruitment, in which Messi, Achraf Hakimi, Gianluigi Donnarumma, Sergio Ramos and Georginio Wijnaldum were brought in, and with Neymar back fit, PSG were widely tipped to seriously challenge for the Champions League."],
  "paragraph19": ["It wasn't to be though as Donnarumma, who has alternated starts with Keylor Navas, was pressured into the error which precipitated PSG's downfall as key players were found wanting when it mattered most."],
  "paragraph20": ["The usually dependable Marquinhos inadvertently teed up Benzema for his third goal, a mere 11 seconds after PSG had kicked off again, as the visitors folded with alarming ease."],
  "paragraph21": ["We were well placed to advance in the Champions League, and with this squad, we believed we could win it, said Leonardo"],
  "paragraph22": ["We must always analyse and look at why things happen this way. But we need time to reflect and move forward."],
  "paragraph23": ["Only time will tell if PSG are afforded the same chance next year."],
  "articleNumber" : "5",
  },
  {
    "title": "Formula One faces its biggest change in decades",
    "date": "15 Mar 2022 10:52PM",
    "h3": ['WHEEL SIZE'],
    "image": ["images/F1 image 1.jpg"],
    "imgDesc": ["Aston Martin's Sebastian Vettel during testing. (Photo: REUTERS/Albert Gea)"],
    "description": "Formula One starts a new season in Bahrain on Sunday with the biggest technical rule change in decades leaving plenty of questions to be answered.",
    "paragraph1": ["Formula One starts a new season in Bahrain on Sunday with the biggest technical rule change in decades leaving plenty of questions to be answered."],
    "paragraph2": ["The cars, heavier and with bigger wheels, look very different to last year's models thanks to an overhaul aimed at making overtaking easier and the racing more competitive and exciting."],
    "paragraph3": ["There is plenty of debate already about the spirit of the rules, to what extent the changes will be successful, how teams have read them and whether some have pushed boundaries too far."],
    "paragraph4": ["This is by far the biggest change in regulation I think the sport has ever seen, commented Aston Martin technical head Andrew Green. My career goes back to 1991 and it trumps anything from 1991."],
    "paragraph5": ["I think it trumps everything as far as F1 is concerned, he added."],
    "paragraph6": ["It’s a completely new concept, a completely different way of approaching a regulation. It’s been a massive challenge. It’s been exciting for sure."],
    "paragraph7": ["Formula One's managing director for motorsport Ross Brawn, another veteran whose career dates back to the 1970s and who has run teams and also served as a Ferrari technical director, hailed a real break with the past."],
    "paragraph8": ["He said the aim was to get a closer competition going on for the future while still leaving it a meritocracy."],
    "paragraph9": ["I think there’ll be a bit of disparity at the beginning but I’m confident these rules and this regime and this culture will lead to much better racing."],
    "paragraph10": ["The most obvious changes are the increase in wheel size from 13 to 18 inches, with low profile Pirelli tyres, and new look front and rear wings designed to reduce the aerodynamic turbulence for cars following behind."],
    "paragraph11": ["There are fairings on the front wheels and radically different interpretations of the sidepods, which are almost non-existent in the case of champions Mercedes, while the floors generate more ground-effect downforce."],
    "paragraph12": ["We may see that we don’t quite hit a bullseye in terms of following (cars) but we’ll still be so massively ahead of where we were, because the (old) cars were dreadful, said Brawn."],
    "paragraph13": ["We’ll still be a long way ahead of where the old cars are and then we’ll evolve it."],
    "paragraph14": ["The race weekend has also been condensed, with media activities moved to Friday from Thursday and more points for the three Saturday sprints to be held in Imola, Austria and Brazil."],
    "paragraph15": ["Each team will also have to run young drivers in two Friday practice sessions over the course of the season."],
    "paragraph16": ["The budget cap, now reduced to US$140 million, has introduced another strategic element."],
    "paragraph17": ["You have to decide extremely carefully where you invest your dollar in R&D. In the past it was a little bit easier because you could follow various avenues in chasing performance, said Mercedes boss Toto Wolff."],
    "paragraph18": ["Today you have to decide which one has the highest potential and then embark on it. So it’s a totally different way of operating for the big teams."],
    "articleNumber" : "6",
  }
];
